""" 
The random.randint function is used to generate a pseudo-random integer between lower_limit and upper_limit.
This is done n times to generate n random numbers.
The generated numbers are stored in the random_numbers list and returned by the function.
Please note that the numbers generated by this program are pseudo-random, 
which means they are generated by a deterministic algorithm and are not truly random. 
However, they should be random enough for most practical purposes.
"""

import random

def generate_random_numbers(n, lower_limit, upper_limit):
    random_numbers = []

    for _ in range(n):
        random_number = random.randint(lower_limit, upper_limit)
        random_numbers.append(random_number)

    return random_numbers

# Generate 10 random numbers between 1 and 100
random_numbers = generate_random_numbers(10, 1, 100)
print(random_numbers)